(setq-default indent-tabs-mode nil)
(setq-default tab-width 2)
(setq js-indent-level 2)
(setq python-indent-offset 2)
(show-paren-mode t)
(global-linum-mode 1)
(setq column-number-mode t)
(put 'upcase-region 'disabled nil)
(ido-mode 1)
(setq ido-enable-flex-matching t)
(setq ido-everywhere t)
(setq inhibit-startup-message t inhibit-startup-echo-area-message t)
(define-key global-map (kbd "RET") 'newline-and-indent)

; add packages
(require 'package)
(add-to-list 'package-archives
             '("melpa" . "https://melpa.org/packages/") t)
(package-initialize)
(package-install 'smartscan)
(package-install 'monokai-theme)
(package-install 'fill-column-indicator)
(package-install 'magit)

(smartscan-mode 1)
(load-theme 'monokai t)
(tool-bar-mode -1)
(menu-bar-mode -1)
(toggle-scroll-bar -1)
(setq-default fill-column 100)
(add-hook 'python-mode-hook (lambda () (fci-mode 1)))
(add-hook 'makrdown-mode-hook (lambda () (fci-mode 1)))
(add-to-list 'default-frame-alist '(height . 60))
(add-to-list 'default-frame-alist '(width . 120))

(global-set-key (kbd "C-x g") 'magit-status)
